apiVersion: v1
kind: Service
metadata:
  name: gnmic
  labels:
    app.kubernetes.io/name: gnmic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gnmic
  ports:
    - name: prom
      port: 9804
      targetPort: prom
      protocol: TCP
