apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi
  monitoring:
    enablePodMonitor: false
