apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clabernetes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/srl-labs/clabernetes
      chart: clabernetes
      targetRevision: 0.5.0
      helm:
        releaseName: clabernetes
        valueFiles:
          - $values/platform/values/clabernetes.yaml
    - repoURL: https://github.com/jp2195/network-automation-demo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: clabernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
