apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbox

resources:
  - seed-job.yaml

configMapGenerator:
  - name: netbox-seed-data
    files:
      - seed.json
  - name: netbox-seed-script
    files:
      - seed.py

generatorOptions:
  disableNameSuffixHash: false
