#!/bin/sh
# /wrapper.sh — generated by tools/render. Do not edit by hand.
set -e

# Install snmpd if it isn't baked in (frrouting/frr is alpine-based).
if ! command -v snmpd >/dev/null 2>&1; then
  apk add --no-cache --quiet net-snmp >/dev/null 2>&1 || true
fi

if command -v snmpd >/dev/null 2>&1; then
  # Don't pass -c: net-snmp's default search already includes
  # /etc/snmp/snmpd.conf, and adding it via -c reads the same file twice,
  # which generates two agentaddress transports and binds udp:161 twice
  # — second bind hits EADDRINUSE and snmpd exits before serving traffic.
  # Background + tolerate failure so a snmpd hiccup never wedges FRR.
  snmpd -Lf /tmp/snmpd.log &
fi

exec /usr/lib/frr/docker-start
