#!/bin/sh
# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.
set -e

# Package installs + telemetry daemons run in the BACKGROUND so that a slow or
# unreachable apk mirror at the boot instant can never block FRR from starting.
# Previously `apk add` ran inline with no timeout; if egress wasn't up yet
# it hung forever, held the apk lock, and wedged the whole cabinet (no FRR, no
# snmpd). Now FRR always comes up and snmpd/rsyslog attach once their package
# lands. busybox provides timeout(1) (verified on the frrouting/frr image).
bootstrap() {
  set +e

  # Wait for egress before hammering apk (up to ~2min), then install each
  # package with a per-attempt timeout and a few retries.
  i=0
  while [ "$i" -lt 24 ]; do
    timeout 8 apk update >/dev/null 2>&1 && break
    i=$((i + 1)); sleep 5
  done

  install_pkg() {  # $1 = binary to probe, $2 = apk package
    command -v "$1" >/dev/null 2>&1 && return 0
    n=0
    while [ "$n" -lt 5 ]; do
      timeout 60 apk add --no-cache --quiet "$2" >/dev/null 2>&1
      command -v "$1" >/dev/null 2>&1 && return 0
      n=$((n + 1)); sleep 3
    done
    return 1
  }

  install_pkg snmpd net-snmp
  install_pkg rsyslogd rsyslog

  # rsyslog forwards FRR daemons' "log syslog informational" output (written
  # to /dev/log via libc syslog(3)) to the alloy-syslog Service over TCP/5514.
  if command -v rsyslogd >/dev/null 2>&1; then
    mkdir -p /etc/rsyslog.d
    cat >/etc/rsyslog.d/50-alloy.conf <<'RSYSLOG'
# imuxsock + imklog are already loaded by /etc/rsyslog.conf (alpine default);
# we only add the forward action here. *.* duplicates the default
# /var/log/messages destination harmlessly.
*.* action(type="omfwd"
          target="alloy-syslog.monitoring.svc.cluster.local"
          port="5514"
          protocol="tcp"
          template="RSYSLOG_SyslogProtocol23Format")
RSYSLOG
    rsyslogd >/tmp/rsyslogd.log 2>&1 &
  fi

  if command -v snmpd >/dev/null 2>&1; then
    # Don't pass -c: net-snmp's default search already includes
    # /etc/snmp/snmpd.conf, and adding it via -c reads the same file twice,
    # which generates two agentaddress transports and binds udp:161 twice
    # — second bind hits EADDRINUSE and snmpd exits before serving traffic.
    snmpd -Lf /tmp/snmpd.log &
  fi
}

bootstrap &

exec /usr/lib/frr/docker-start
