apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    alert:
      port: "12000"
      endpoint: /alert
      method: POST
    manual-cut:
      port: "12000"
      endpoint: /manual-cut
      method: POST
    gray-failure:
      port: "12000"
      endpoint: /gray-failure
      method: POST
    maintenance:
      port: "12000"
      endpoint: /maintenance
      method: POST
