name: dom-synth
namespace: monitoring
syncWave: "2"
path: workloads/dom-synth
automated: false
ignoreDifferences:
  - group: monitoring.coreos.com
    kind: ServiceMonitor
    jqPathExpressions:
      - .spec.endpoints[].metricRelabelings[].action
