name: gnmic
namespace: monitoring
syncWave: "2"
appPath: workloads/gnmic
ignoreDifferences:
  - group: monitoring.coreos.com
    kind: ServiceMonitor
    jqPathExpressions:
      - .spec.endpoints[].metricRelabelings[].action
