apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: dom-synth-script
    files:
      - dom_synth.py
  - name: dom-synth-links
    files:
      - links.json
