apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  labels:
    app.kubernetes.io/name: snmp-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: snmp-exporter
  ports:
    - name: http
      port: 9116
      targetPort: http
      protocol: TCP
