package main

import (
	"fmt"
	"io"
)

func WriteFRR(w io.Writer, n *Node, s *Spec) error {
	p := func(format string, args ...interface{}) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("! %s — %s", n.Name, n.Description)
	p("! Site: %s, %s (lat=%.4f lon=%.4f)", n.Site.City, n.Site.Label, n.Site.Lat, n.Site.Lon)
	p("! Generated by tools/render — do not edit by hand. Source: spec/atlanta.yaml")
	p("!")
	p("frr version 9.1")
	p("frr defaults traditional")
	p("hostname %s", n.Name)
	p("log syslog informational")
	p("log file /var/log/frr/frr.log")
	p("service integrated-vtysh-config")
	p("!")

	p("interface lo")
	p(" ip address %s/32", n.LoopbackV4)
	p("!")

	ifaces := s.InterfacesOf(n.Name)
	for _, ifc := range ifaces {
		peerNode := s.NodeByName(ifc.PeerNode)
		peerCity := ""
		if peerNode != nil {
			peerCity = peerNode.Site.City
		}
		p("interface %s", ifc.Name)
		p(" description to %s/%s [%s] %s", ifc.PeerNode, ifc.PeerIntf, ifc.Cable.Label, peerCity)
		p(" ip address %s/30", ifc.LocalV4)
		p("!")
	}

	p("router bgp %d", n.ASN)
	p(" bgp router-id %s", n.LoopbackV4)
	p(" no bgp ebgp-requires-policy")
	for _, ifc := range ifaces {
		peerNode := s.NodeByName(ifc.PeerNode)
		asn := s.Metadata.ASN.Backbone
		if peerNode != nil && peerNode.ASN != 0 {
			asn = peerNode.ASN
		}
		p(" neighbor %s remote-as %d", ifc.PeerV4, asn)
		p(" neighbor %s description %s", ifc.PeerV4, ifc.PeerNode)
	}
	p(" !")
	p(" address-family ipv4 unicast")
	p("  network %s/32", n.LoopbackV4)
	p(" exit-address-family")
	p("!")

	var parentV4 string
	for _, ifc := range ifaces {
		if ifc.PeerNode == n.ParentHub {
			parentV4 = ifc.PeerV4
			break
		}
	}
	if parentV4 != "" {
		p("ip route 0.0.0.0/0 %s", parentV4)
		p("!")
	}

	return nil
}
