package main

import (
	"fmt"
	"io"
)

func WriteGNMIC(w io.Writer, s *Spec) error {
	p := func(format string, args ...interface{}) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("# gNMIc target list — generated by tools/render. Source: spec/atlanta.yaml")
	p("# Cabinets (FRR) are not subscribed (no gNMI on FRR).")
	p("")
	p("username: admin")
	p("password: NokiaSrl1!")
	p("skip-verify: true")
	p("encoding: json_ietf")
	p("")
	p("targets:")

	for _, n := range s.Nodes {
		if n.Kind != "srlinux" {
			continue
		}
		// Clabernetes default `naming: prefixed` exposes each topology node as a
		// Service named `<topology>-<node>` in the topology's namespace.
		addr := fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local:57400", s.Metadata.Name, n.Name)
		p("  %s:", addr)
		p("    tags:")
		p("      - role=%s", n.Role)
		p("      - site=%s", n.Site.Label)
		p("      - city=%s", n.Site.City)
		if n.Site.Corridor != "" {
			p("      - corridor=%s", n.Site.Corridor)
		}
		p("      - lat=%.4f", n.Site.Lat)
		p("      - lon=%.4f", n.Site.Lon)
		p("      - district=%d", n.Site.District)
		p("      - sid=%d", n.ISISSID)
	}
	p("")
	p("subscriptions:")
	// Paths use SR Linux native YANG (srl_nokia-*), not OpenConfig. SRL
	// answers gNMI in its native model by default; OpenConfig translation
	// would need an explicit yang-models config on the box.
	//
	// Fast: interface state changes — drives InterfaceDown alert + state panels.
	p("  if-state:")
	p("    paths:")
	p("      - /interface/oper-state")
	p("      - /interface/admin-state")
	p("      - /interface/last-change")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 5s")
	// Medium: traffic + error/discard counters. Drives traffic graphs +
	// flapping/error-rate alerts. 10s aligns with Prometheus scrape.
	p("  if-counters:")
	p("    paths:")
	p("      - /interface/statistics/in-octets")
	p("      - /interface/statistics/out-octets")
	p("      - /interface/statistics/in-unicast-packets")
	p("      - /interface/statistics/out-unicast-packets")
	p("      - /interface/statistics/in-multicast-packets")
	p("      - /interface/statistics/out-multicast-packets")
	p("      - /interface/statistics/in-broadcast-packets")
	p("      - /interface/statistics/out-broadcast-packets")
	p("      - /interface/statistics/in-error-packets")
	p("      - /interface/statistics/out-error-packets")
	p("      - /interface/statistics/in-discarded-packets")
	p("      - /interface/statistics/out-discarded-packets")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 10s")
	// Slow: control-plane health. CPU + memory under SR Linux's
	// platform/control[slot=*] node.
	p("  system:")
	p("    paths:")
	p("      - /platform/control/cpu/total")
	p("      - /platform/control/memory")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 60s")
	p("")
	p("")
	// SR Linux returns oper-state and admin-state as enum strings (\"up\"/\"down\"
	// and \"enable\"/\"disable\"). gnmic's prometheus output drops non-numeric
	// values, so map them to ints via event processors before exposing.
	p("processors:")
	p("  oper-state-to-int:")
	p("    event-strings:")
	p("      value-names:")
	p("        - \".*oper.state.*\"")
	p("      transforms:")
	p("        - replace:")
	p("            apply-on: value")
	p("            old: up")
	p("            new: \"1\"")
	p("        - replace:")
	p("            apply-on: value")
	p("            old: down")
	p("            new: \"2\"")
	p("  admin-state-to-int:")
	p("    event-strings:")
	p("      value-names:")
	p("        - \".*admin.state.*\"")
	p("      transforms:")
	p("        - replace:")
	p("            apply-on: value")
	p("            old: enable")
	p("            new: \"1\"")
	p("        - replace:")
	p("            apply-on: value")
	p("            old: disable")
	p("            new: \"0\"")
	p("  state-cast:")
	p("    event-convert:")
	p("      values:")
	p("        - \".*oper.state.*\"")
	p("        - \".*admin.state.*\"")
	p("      type: int")
	p("")
	// metric-prefix is intentionally omitted: gnmic's path encoding already
	// produces names like `srl_nokia_interfaces_interface_*` from the YANG
	// module prefix, so an extra prefix would just yield `srl_srl_nokia_*`.
	p("outputs:")
	p("  prom:")
	p("    type: prometheus")
	p("    listen: \":9804\"")
	p("    event-processors:")
	p("      - oper-state-to-int")
	p("      - admin-state-to-int")
	p("      - state-cast")
	return nil
}
