package main

import (
	"fmt"
	"io"
)

func WriteGNMIC(w io.Writer, s *Spec) error {
	p := func(format string, args ...interface{}) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# gNMIc target list — generated by tools/render. Source: spec/atlanta.yaml")
	p("# Cabinets (FRR) are not subscribed (no gNMI on FRR).")
	p("")
	p("username: admin")
	p("password: NokiaSrl1!")
	p("skip-verify: true")
	p("encoding: json_ietf")
	p("")
	p("targets:")

	for _, n := range s.Nodes {
		if n.Kind != "srlinux" {
			continue
		}
		// Clabernetes default `naming: prefixed` exposes each topology node as a
		// Service named `<topology>-<node>` in the topology's namespace.
		addr := fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local:57400", s.Metadata.Name, n.Name)
		p("  %s:", addr)
		p("    tags:")
		p("      - role=%s", n.Role)
		p("      - site=%s", n.Site.Label)
		p("      - city=%s", n.Site.City)
		if n.Site.Corridor != "" {
			p("      - corridor=%s", n.Site.Corridor)
		}
		p("      - lat=%.4f", n.Site.Lat)
		p("      - lon=%.4f", n.Site.Lon)
		p("      - district=%d", n.Site.District)
		p("      - sid=%d", n.ISISSID)
	}
	p("")
	p("subscriptions:")
	// Paths use SR Linux native YANG (srl_nokia-*), not OpenConfig. SRL
	// answers gNMI in its native model by default; OpenConfig translation
	// would need an explicit yang-models config on the box.
	//
	// Fast: interface state changes — drives InterfaceDown alert + state panels.
	p("  if-state:")
	p("    paths:")
	p("      - /interface/oper-state")
	p("      - /interface/admin-state")
	p("      - /interface/last-change")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 5s")
	// Medium: traffic + error/discard counters. Drives traffic graphs +
	// flapping/error-rate alerts. 10s aligns with Prometheus scrape.
	p("  if-counters:")
	p("    paths:")
	p("      - /interface/statistics/in-octets")
	p("      - /interface/statistics/out-octets")
	p("      - /interface/statistics/in-unicast-packets")
	p("      - /interface/statistics/out-unicast-packets")
	p("      - /interface/statistics/in-multicast-packets")
	p("      - /interface/statistics/out-multicast-packets")
	p("      - /interface/statistics/in-broadcast-packets")
	p("      - /interface/statistics/out-broadcast-packets")
	p("      - /interface/statistics/in-error-packets")
	p("      - /interface/statistics/out-error-packets")
	p("      - /interface/statistics/in-discarded-packets")
	p("      - /interface/statistics/out-discarded-packets")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 10s")
	// Slow: control-plane health. CPU + memory under SR Linux's
	// platform/control[slot=*] node.
	p("  system:")
	p("    paths:")
	p("      - /platform/control/cpu/total")
	p("      - /platform/control/memory")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 60s")
	p("")
	p("outputs:")
	p("  prom:")
	p("    type: prometheus")
	p("    listen: \":9804\"")
	p("    metric-prefix: srl")
	return nil
}
