package main

import (
	"fmt"
	"io"
)

func WriteGNMIC(w io.Writer, s *Spec) error {
	p := func(format string, args ...interface{}) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# gNMIc target list — generated by tools/render. Source: spec/atlanta.yaml")
	p("# Cabinets (FRR) are not subscribed (no gNMI on FRR).")
	p("")
	p("username: admin")
	p("password: NokiaSrl1!")
	p("skip-verify: true")
	p("encoding: json_ietf")
	p("")
	p("targets:")

	for _, n := range s.Nodes {
		if n.Kind != "srlinux" {
			continue
		}
		// Clabernetes default `naming: prefixed` exposes each topology node as a
		// Service named `<topology>-<node>` in the topology's namespace.
		addr := fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local:57400", s.Metadata.Name, n.Name)
		p("  %s:", addr)
		p("    tags:")
		p("      role: %s", n.Role)
		p("      site: %s", n.Site.Label)
		p("      city: %q", n.Site.City)
		if n.Site.Corridor != "" {
			p("      corridor: %q", n.Site.Corridor)
		}
		p("      lat: %q", fmt.Sprintf("%.4f", n.Site.Lat))
		p("      lon: %q", fmt.Sprintf("%.4f", n.Site.Lon))
		p("      district: %q", fmt.Sprintf("%d", n.Site.District))
		p("      sid: %q", fmt.Sprintf("%d", n.ISISSID))
	}
	p("")
	p("subscriptions:")
	p("  ifstate:")
	p("    paths:")
	p("      - /interfaces/interface/state/oper-status")
	p("      - /interfaces/interface/state/admin-status")
	p("      - /interfaces/interface/state/counters/in-octets")
	p("      - /interfaces/interface/state/counters/out-octets")
	p("      - /interfaces/interface/state/counters/in-error-packets")
	p("      - /interfaces/interface/state/counters/out-error-packets")
	p("      - /interfaces/interface/transceiver/state/input-power")
	p("      - /interfaces/interface/transceiver/state/output-power")
	p("      - /interfaces/interface/transceiver/state/module-temperature")
	p("    mode: stream")
	p("    stream-mode: sample")
	p("    sample-interval: 10s")
	p("")
	p("outputs:")
	p("  prom:")
	p("    type: prometheus")
	p("    listen: \":9804\"")
	p("    metric-prefix: srl")
	return nil
}
