package main

import "io"

// WriteLinkRateRules emits four recording rules that pre-compute the
// joins dashboards currently repeat. Naming follows Prometheus's
// recommended `level:metric:operations` style.
//
//	link:oper_state_with_meta  — canonical join, lifts link_id, link_kind,
//	  corridor, cable_label, provider, restoration_sla_hours, site, city,
//	  role from link_membership_info onto srl_nokia oper_state samples.
//	link:rate_in_bps:1m        — sum-by-link 1m rate of in_octets * 8.
//	link:rate_out_bps:1m       — sum-by-link 1m rate of out_octets * 8.
//	link:p95_out_bps:30m       — 95th-percentile of the above over 30m.
//
// Eval every 30s.
func WriteLinkRateRules(w io.Writer, _ *Spec) error {
	p := newPrinter(w)
	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("apiVersion: monitoring.coreos.com/v1")
	p("kind: PrometheusRule")
	p("metadata:")
	p("  name: link-rate-rules")
	p("  labels:")
	p("    app.kubernetes.io/name: link-rate-rules")
	p("    release: kps")
	p("spec:")
	p("  groups:")
	p("    - name: link-rate")
	p("      interval: 30s")
	p("      rules:")
	p("        - record: link:oper_state_with_meta")
	p("          expr: |")
	p("            srl_nokia_interfaces_interface_oper_state")
	p("              * on(node, interface)")
	p("              group_left(link_id, link_kind, corridor, cable_label, provider,")
	p("                         restoration_sla_hours, site, city, role)")
	p("            link_membership_info")
	p("        - record: link:rate_in_bps:1m")
	p("          expr: |")
	p("            sum by (link_id, link_kind, corridor) (")
	p("              rate(srl_nokia_interfaces_interface_statistics_in_octets[1m])")
	p("                * on(node, interface)")
	p("                group_left(link_id, link_kind, corridor)")
	p("              link_membership_info")
	p("            ) * 8")
	p("        - record: link:rate_out_bps:1m")
	p("          expr: |")
	p("            sum by (link_id, link_kind, corridor) (")
	p("              rate(srl_nokia_interfaces_interface_statistics_out_octets[1m])")
	p("                * on(node, interface)")
	p("                group_left(link_id, link_kind, corridor)")
	p("              link_membership_info")
	p("            ) * 8")
	p("        - record: link:p95_out_bps:30m")
	p("          expr: |")
	p("            quantile_over_time(0.95, link:rate_out_bps:1m[30m])")
	return nil
}
