package main

import (
	"fmt"
	"io"
)

// snmpCommunity is the read-only SNMPv2c community used for the demo.
// Matches the `public_v2` auth in snmp_exporter's bundled snmp.yml so we
// can use the upstream-shipped module config without a hand-rolled override.
const snmpCommunity = "public"

// frrSNMPDConf is the snmpd configuration baked into the FRR cabinet
// containers. Listens on 161 on all interfaces, allows the demo community
// read-only access, exports system + interface MIBs.
const frrSNMPDConf = `# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.
syslocation "Atlas DOT Region 7 — field cabinet"
syscontact  "noc@adot.local"

agentaddress udp:161

# Read-only access for the demo community from anywhere in the cluster.
rocommunity ` + snmpCommunity + ` default

# Cap the OIDs we expose to system + interface MIBs (everything the
# Prometheus snmp_exporter if_mib module walks).
view ifview included .1.3.6.1.2.1.1
view ifview included .1.3.6.1.2.1.2
view ifview included .1.3.6.1.2.1.31

# Avoid noisy log files; stderr goes to docker logs.
dontLogTCPWrappersConnects yes
`

// frrWrapper is the entrypoint script bound into FRR cabinet containers.
// Launches snmpd in the background before handing off to FRR's
// docker-start as PID 1. net-snmp is pre-baked into the image.
const frrWrapper = `#!/bin/sh
# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.
set -e

# net-snmp is baked into the atlas-demo-registry:5001/frr-snmpd image
# (see images/frr-snmpd/Dockerfile). Background snmpd before exec'ing
# docker-start. Don't pass -c: the default search already includes
# /etc/snmp/snmpd.conf, so explicit -c reads it twice and the second
# udp:161 bind hits EADDRINUSE. Tolerate failure so a snmpd hiccup
# never wedges FRR.
snmpd -Lf /tmp/snmpd.log &

exec /usr/lib/frr/docker-start
`

// WriteSNMPDConf writes the shared snmpd.conf for FRR cabinets.
func WriteSNMPDConf(w io.Writer) error {
	_, err := io.WriteString(w, frrSNMPDConf)
	return err
}

// WriteFRRWrapper writes the FRR cabinet entrypoint wrapper script.
func WriteFRRWrapper(w io.Writer) error {
	_, err := io.WriteString(w, frrWrapper)
	return err
}

// FRRSNMPTargets returns the list of in-cluster DNS addresses for the FRR
// cabinet pods, matching clabernetes' default `naming: prefixed` scheme.
// Used by the SNMP workload's Probe CR.
func FRRSNMPTargets(s *Spec) []string {
	var out []string
	for _, n := range s.Nodes {
		if n.Kind != KindFRR {
			continue
		}
		out = append(out, fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local", s.Metadata.Name, n.Name))
	}
	return out
}
