package main

import (
	"fmt"
	"io"
)

// WriteSNMPProbe emits the Probe CR scraped by snmp_exporter against the
// FRR cabinet pods. Targets are derived from FRRSNMPTargets so new
// cabinets added to the spec appear automatically.
func WriteSNMPProbe(w io.Writer, s *Spec) error {
	p := newPrinter(w)
	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("apiVersion: monitoring.coreos.com/v1")
	p("kind: Probe")
	p("metadata:")
	p("  name: snmp-frr-cabinets")
	p("  labels:")
	p("    release: kps")
	p("spec:")
	p("  jobName: snmp-frr-cabinets")
	p("  interval: 30s")
	p("  scrapeTimeout: 25s")
	p("  module: if_mib")
	p("  prober:")
	p("    url: snmp-exporter.monitoring.svc.cluster.local:9116")
	p("    path: /snmp")
	p("  targets:")
	p("    staticConfig:")
	p("      # Targets the standard SNMP port (161/udp). See snmp_render.go's")
	p("      # FRRSNMPTargets for the FQDN derivation.")
	p("      static:")
	for _, t := range FRRSNMPTargets(s) {
		p("        - %s:161", t)
	}
	p("      labels:")
	p("        telemetry_source: snmp")
	p("        node_role: field-cabinet")
	p("      relabelingConfigs:")
	p("        # Promote the cabinet hostname from the target FQDN into a")
	p("        # `node` label so it joins with link_membership_info.")
	p("        - sourceLabels: [__param_target]")
	p("          regex: %q", fmt.Sprintf(`%s-(fc-[a-z0-9]+)\.clabernetes\.svc\.cluster\.local:[0-9]+`, s.Metadata.Name))
	p("          targetLabel: node")
	p("          replacement: \"$1\"")
	p("        - targetLabel: __param_auth")
	p("          replacement: public_v2")
	return nil
}
