package main

import (
	"fmt"
	"io"
)

// snmpCommunity is the read-only SNMPv2c community used for the demo.
// Documented as a demo string in SECRETS.md; not a real credential.
const snmpCommunity = "demo-public"

// frrSNMPDConf is the snmpd configuration baked into the FRR cabinet
// containers. Listens on 161 on all interfaces, allows the demo community
// read-only access, exports system + interface MIBs.
const frrSNMPDConf = `# /etc/snmp/snmpd.conf — generated by tools/render. Do not edit by hand.
syslocation "Atlas DOT Region 7 — field cabinet"
syscontact  "noc@adot.local"

agentaddress udp:161,udp6:[::]:161

# Read-only access for the demo community from anywhere in the cluster.
rocommunity ` + snmpCommunity + ` default

# Cap the OIDs we expose to system + interface MIBs (everything the
# Prometheus snmp_exporter if_mib module walks).
view ifview included .1.3.6.1.2.1.1
view ifview included .1.3.6.1.2.1.2
view ifview included .1.3.6.1.2.1.31

# Avoid noisy log files; stderr goes to docker logs.
dontLogTCPWrappersConnects yes
`

// frrWrapper is the entrypoint script bound into FRR cabinet containers.
// Installs net-snmp on first boot (alpine apk), starts snmpd in the
// background, then hands off to FRR's docker-start as PID 1.
const frrWrapper = `#!/bin/sh
# /wrapper.sh — generated by tools/render. Do not edit by hand.
set -e

# Install snmpd if it isn't baked in (frrouting/frr is alpine-based).
if ! command -v snmpd >/dev/null 2>&1; then
  apk add --no-cache --quiet net-snmp >/dev/null 2>&1 || true
fi

if command -v snmpd >/dev/null 2>&1; then
  snmpd -c /etc/snmp/snmpd.conf -Lf /tmp/snmpd.log
fi

exec /usr/lib/frr/docker-start
`

// WriteSNMPDConf writes the shared snmpd.conf for FRR cabinets.
func WriteSNMPDConf(w io.Writer) error {
	_, err := io.WriteString(w, frrSNMPDConf)
	return err
}

// WriteFRRWrapper writes the FRR cabinet entrypoint wrapper script.
func WriteFRRWrapper(w io.Writer) error {
	_, err := io.WriteString(w, frrWrapper)
	return err
}

// FRRSNMPTargets returns the list of in-cluster DNS addresses for the FRR
// cabinet pods, matching clabernetes' default `naming: prefixed` scheme.
// Used by the SNMP workload's Probe CR.
func FRRSNMPTargets(s *Spec) []string {
	var out []string
	for _, n := range s.Nodes {
		if n.Kind != "frr" {
			continue
		}
		out = append(out, fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local", s.Metadata.Name, n.Name))
	}
	return out
}
