package main

import (
	"fmt"
	"io"
)

// snmpCommunity is the read-only SNMPv2c community used for the demo.
// Matches the `public_v2` auth in snmp_exporter's bundled snmp.yml so we
// can use the upstream-shipped module config without a hand-rolled override.
const snmpCommunity = "public"

// frrSNMPDConf is the snmpd configuration baked into the FRR cabinet
// containers. Listens on 161 on all interfaces, allows the demo community
// read-only access, exports system + interface MIBs.
const frrSNMPDConf = `# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.
syslocation "Atlas DOT Region 7 — field cabinet"
syscontact  "noc@adot.local"

agentaddress udp:161

# Read-only access for the demo community from anywhere in the cluster.
rocommunity ` + snmpCommunity + ` default

# Cap the OIDs we expose to system + interface MIBs (everything the
# Prometheus snmp_exporter if_mib module walks).
view ifview included .1.3.6.1.2.1.1
view ifview included .1.3.6.1.2.1.2
view ifview included .1.3.6.1.2.1.31

# Avoid noisy log files; stderr goes to docker logs.
dontLogTCPWrappersConnects yes
`

// frrWrapper is the entrypoint script bound into FRR cabinet containers.
// Installs snmpd on first boot (alpine apk), starts snmpd in the
// background, then hands off to FRR's docker-start as PID 1. The
// pre-baked frr-snmpd image (images/frr-snmpd/Dockerfile) exists for
// future use but is not in the Topology — clabernetes' containerlab
// can't resolve atlas-demo-registry:5001/... refs from nested docker.
const frrWrapper = `#!/bin/sh
# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.
set -e

# Install snmpd if it isn't baked in (frrouting/frr is alpine-based).
if ! command -v snmpd >/dev/null 2>&1; then
  apk add --no-cache --quiet net-snmp >/dev/null 2>&1 || true
fi

# Install rsyslog so FRR daemons' "log syslog informational" output
# (currently writing to /dev/log via libc syslog(3)) reaches the
# alloy-syslog Service. imuxsock listens on /dev/log; the action line
# forwards every message over TCP/5514 in RFC5424.
if ! command -v rsyslogd >/dev/null 2>&1; then
  apk add --no-cache --quiet rsyslog >/dev/null 2>&1 || true
fi

if command -v rsyslogd >/dev/null 2>&1; then
  cat >/etc/rsyslog.d/50-alloy.conf <<'RSYSLOG'
# imuxsock + imklog are already loaded by /etc/rsyslog.conf (alpine default);
# we only add the forward action here. *.* duplicates the default
# /var/log/messages destination harmlessly.
*.* action(type="omfwd"
          target="alloy-syslog.monitoring.svc.cluster.local"
          port="5514"
          protocol="tcp"
          template="RSYSLOG_SyslogProtocol23Format")
RSYSLOG
  # rsyslogd daemonizes by default (no -n), so the trailing & is belt
  # and suspenders; redirect output so a syslog hiccup never wedges FRR.
  rsyslogd >/tmp/rsyslogd.log 2>&1 &
fi

if command -v snmpd >/dev/null 2>&1; then
  # Don't pass -c: net-snmp's default search already includes
  # /etc/snmp/snmpd.conf, and adding it via -c reads the same file twice,
  # which generates two agentaddress transports and binds udp:161 twice
  # — second bind hits EADDRINUSE and snmpd exits before serving traffic.
  # Background + tolerate failure so a snmpd hiccup never wedges FRR.
  snmpd -Lf /tmp/snmpd.log &
fi

exec /usr/lib/frr/docker-start
`

// WriteSNMPDConf writes the shared snmpd.conf for FRR cabinets.
func WriteSNMPDConf(w io.Writer) error {
	_, err := io.WriteString(w, frrSNMPDConf)
	return err
}

// WriteFRRWrapper writes the FRR cabinet entrypoint wrapper script.
func WriteFRRWrapper(w io.Writer) error {
	_, err := io.WriteString(w, frrWrapper)
	return err
}

// FRRSNMPTargets returns the list of in-cluster DNS addresses for the FRR
// cabinet pods, matching clabernetes' default `naming: prefixed` scheme.
// Used by the SNMP workload's Probe CR.
func FRRSNMPTargets(s *Spec) []string {
	var out []string
	for _, n := range s.Nodes {
		if n.Kind != KindFRR {
			continue
		}
		out = append(out, fmt.Sprintf("%s-%s.clabernetes.svc.cluster.local", s.Metadata.Name, n.Name))
	}
	return out
}
