package main

import (
	"fmt"
	"io"
)

func WriteSRL(w io.Writer, n *Node, s *Spec) error {
	p := func(format string, args ...interface{}) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# %s — %s", n.Name, n.Description)
	p("# Site: %s, %s (lat=%.4f lon=%.4f), %s", n.Site.City, n.Site.Label, n.Site.Lat, n.Site.Lon, s.DOT.Region)
	p("# Generated by tools/render — do not edit by hand. Source: spec/atlanta.yaml")
	p("")

	p("set / system name host-name %s", n.Name)
	p("")

	syslog := "alloy-syslog.observability.svc.cluster.local"
	p("set / system logging network-instance default")
	p("set / system logging remote-server %s transport udp", syslog)
	p("set / system logging remote-server %s remote-port 514", syslog)
	p("")

	p("set / interface lo0 admin-state enable")
	p("set / interface lo0 subinterface 0 admin-state enable")
	p("set / interface lo0 subinterface 0 ipv4 admin-state enable")
	p("set / interface lo0 subinterface 0 ipv4 address %s/32", n.LoopbackV4)
	p("")

	ifaces := s.InterfacesOf(n.Name)
	hasCabinet := false
	for _, ifc := range ifaces {
		peerNode := s.NodeByName(ifc.PeerNode)
		peerCity := ""
		if peerNode != nil {
			peerCity = peerNode.Site.City
		}
		p("set / interface %s description \"to %s/%s [%s] %s\"", ifc.Name, ifc.PeerNode, ifc.PeerIntf, ifc.Cable.Label, peerCity)
		p("set / interface %s admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 ipv4 admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 ipv4 address %s/30", ifc.Name, ifc.LocalV4)
		p("")
		if ifc.LinkKind == "cabinet" {
			hasCabinet = true
		}
	}

	p("set / network-instance default type default")
	p("set / network-instance default router-id %s", n.LoopbackV4)
	p("set / network-instance default interface lo0.0")
	for _, ifc := range ifaces {
		p("set / network-instance default interface %s.0", ifc.Name)
	}
	p("")

	netID := ISISNet(s.Metadata.ISIS.Area, n.LoopbackV4)
	isisLevel := s.Metadata.ISIS.Level
	if isisLevel == "" {
		isisLevel = "L2"
	}

	p("set / network-instance default protocols isis instance atlas admin-state enable")
	p("set / network-instance default protocols isis instance atlas level-capability %s", isisLevel)
	p("set / network-instance default protocols isis instance atlas net [ \"%s\" ]", netID)
	p("set / network-instance default protocols isis instance atlas ipv4-unicast admin-state enable")
	p("set / network-instance default protocols isis instance atlas interface lo0.0 admin-state enable")
	p("set / network-instance default protocols isis instance atlas interface lo0.0 passive true")
	p("set / network-instance default protocols isis instance atlas interface lo0.0 ipv4-unicast admin-state enable")
	for _, ifc := range ifaces {
		if ifc.LinkKind != "backbone" {
			continue
		}
		p("set / network-instance default protocols isis instance atlas interface %s.0 admin-state enable", ifc.Name)
		p("set / network-instance default protocols isis instance atlas interface %s.0 ipv4-unicast admin-state enable", ifc.Name)
		p("set / network-instance default protocols isis instance atlas interface %s.0 circuit-type point-to-point", ifc.Name)
	}
	p("")

	// SR-MPLS / prefix-SID config is intentionally absent. The public
	// ghcr.io/nokia/srlinux image does not advertise the `mpls` or
	// `segment-routing` base features on any 7220 IXR chassis, so the YANG
	// containers (`network-instance/segment-routing`, `mpls`) are not
	// instantiable. The narrative still positions the backbone as SR-MPLS in
	// design — runtime forwarding falls back to plain IS-IS / IPv4.


	isTMC := n.Role == "tmc"
	if hasCabinet || isTMC {
		p("set / network-instance default protocols bgp admin-state enable")
		p("set / network-instance default protocols bgp autonomous-system %d", s.Metadata.ASN.Backbone)
		p("set / network-instance default protocols bgp router-id %s", n.LoopbackV4)
		p("set / network-instance default protocols bgp afi-safi ipv4-unicast admin-state enable")
		p("")
	}

	if hasCabinet {
		p("set / routing-policy policy export-cabinet-routes statement 10 match protocol isis")
		p("set / routing-policy policy export-cabinet-routes statement 10 action policy-result accept")
		p("set / network-instance default protocols bgp group cabinets afi-safi ipv4-unicast admin-state enable")
		p("set / network-instance default protocols bgp group cabinets export-policy [export-cabinet-routes]")
		p("")
		for _, ifc := range ifaces {
			if ifc.LinkKind != "cabinet" {
				continue
			}
			peerNode := s.NodeByName(ifc.PeerNode)
			asn := 0
			peerCity := ""
			if peerNode != nil {
				asn = peerNode.ASN
				peerCity = peerNode.Site.City
			}
			p("set / network-instance default protocols bgp neighbor %s admin-state enable", ifc.PeerV4)
			p("set / network-instance default protocols bgp neighbor %s peer-as %d", ifc.PeerV4, asn)
			p("set / network-instance default protocols bgp neighbor %s peer-group cabinets", ifc.PeerV4)
			p("set / network-instance default protocols bgp neighbor %s description \"%s (%s)\"", ifc.PeerV4, ifc.PeerNode, peerCity)
			p("")
		}
	}

	if isTMC {
		p("set / network-instance default protocols bgp group tmc-ibgp afi-safi ipv4-unicast admin-state enable")
		for _, peer := range s.Nodes {
			if peer.Role != "tmc" || peer.Name == n.Name {
				continue
			}
			p("set / network-instance default protocols bgp neighbor %s admin-state enable", peer.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s peer-as %d", peer.LoopbackV4, s.Metadata.ASN.Backbone)
			p("set / network-instance default protocols bgp neighbor %s peer-group tmc-ibgp", peer.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s transport local-address %s", peer.LoopbackV4, n.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s description \"iBGP to %s\"", peer.LoopbackV4, peer.Name)
			p("")
		}
	}

	return nil
}
