package main

import (
	"io"
)

func WriteSRL(w io.Writer, n *Node, s *Spec) error {
	p := newPrinter(w)

	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("# %s — %s", n.Name, n.Description)
	p("# Site: %s, %s (lat=%.4f lon=%.4f), %s", n.Site.City, n.Site.Label, n.Site.Lat, n.Site.Lon, s.DOT.Region)
	p("")

	p("set / system name host-name %s", n.Name)
	p("")

	// Syslog goes out via the mgmt network-instance — the only VRF on
	// these nodes with an IPv4 address (172.20.20.2/24) and a default
	// route (172.20.20.1, the clabernetes launcher bridge). UDP is the
	// only viable transport: TCP from inside srbase-mgmt netns can't
	// receive a SYN-ACK because SRL doesn't reclassify arriving replies
	// back into the VRF netns. UDP needs no return packet.
	syslog := AlloySyslogHost
	p("set / system logging network-instance mgmt")
	p("set / system logging remote-server %s transport udp", syslog)
	p("set / system logging remote-server %s remote-port %s", syslog, AlloySyslogPort)
	// SRL parses the remote-server block but won't actually forward
	// anything unless at least one facility/priority filter is wired up.
	// Forwarding "all" facilities at info+ matches the file/buffer
	// pipelines SRL ships by default.
	p("set / system logging remote-server %s facility all priority match-above informational", syslog)
	p("")

	// Named operator accounts for change attribution. A role must grant the
	// gnmi/json-rpc/cli services explicitly — superuser alone yields a gNMI
	// PermissionDenied ("not authorized to use service srlinux-gnmi"). With
	// the services granted, a Set authenticated as one of these users is
	// logged by sr_aaa_mgr / sr_mgmt_server as "committed ... by user <name>
	// from host <ip>", which flows to Loki — so the demo can show WHO made a
	// change (noc-ops = manual cut, svc-automation = closed-loop remediation)
	// rather than the generic admin/root. Demo passwords (see SECRETS.md).
	for _, u := range []struct{ user, pass string }{
		{NocOpsUser, NocOpsPassword},
		{AutomationUser, AutomationPassword},
	} {
		p("set / system aaa authorization role %s superuser true", u.user)
		p("set / system aaa authorization role %s services [ cli gnmi json-rpc ]", u.user)
		p("set / system aaa authentication user %s role [ %s ]", u.user, u.user)
		p("set / system aaa authentication user %s password %s", u.user, u.pass)
	}
	p("")

	p("set / interface lo0 admin-state enable")
	p("set / interface lo0 subinterface 0 admin-state enable")
	p("set / interface lo0 subinterface 0 ipv4 admin-state enable")
	p("set / interface lo0 subinterface 0 ipv4 address %s/32", n.LoopbackV4)
	p("")

	ifaces := s.InterfacesOf(n.Name)
	hasCabinet := false
	for _, ifc := range ifaces {
		peerNode := s.NodeByName(ifc.PeerNode)
		peerCity := ""
		if peerNode != nil {
			peerCity = peerNode.Site.City
		}
		p("set / interface %s description \"to %s/%s [%s] %s\"", ifc.Name, ifc.PeerNode, ifc.PeerIntf, ifc.Cable.Label, peerCity)
		p("set / interface %s admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 ipv4 admin-state enable", ifc.Name)
		p("set / interface %s subinterface 0 ipv4 address %s/30", ifc.Name, ifc.LocalV4)
		p("")
		if ifc.LinkKind == LinkKindCabinet {
			hasCabinet = true
		}
	}

	p("set / network-instance default type default")
	p("set / network-instance default router-id %s", n.LoopbackV4)
	p("set / network-instance default interface lo0.0")
	for _, ifc := range ifaces {
		p("set / network-instance default interface %s.0", ifc.Name)
	}
	p("")

	netID := ISISNet(s.Metadata.ISIS.Area, n.LoopbackV4)
	isisLevel := s.Metadata.ISIS.Level
	if isisLevel == "" {
		isisLevel = "L2"
	}

	p("set / network-instance default protocols isis instance %s admin-state enable", ISISInstance)
	p("set / network-instance default protocols isis instance %s level-capability %s", ISISInstance, isisLevel)
	p("set / network-instance default protocols isis instance %s net [ \"%s\" ]", ISISInstance, netID)
	p("set / network-instance default protocols isis instance %s ipv4-unicast admin-state enable", ISISInstance)
	p("set / network-instance default protocols isis instance %s interface lo0.0 admin-state enable", ISISInstance)
	p("set / network-instance default protocols isis instance %s interface lo0.0 passive true", ISISInstance)
	p("set / network-instance default protocols isis instance %s interface lo0.0 ipv4-unicast admin-state enable", ISISInstance)
	for _, ifc := range ifaces {
		if ifc.LinkKind != LinkKindBackbone {
			continue
		}
		p("set / network-instance default protocols isis instance %s interface %s.0 admin-state enable", ISISInstance, ifc.Name)
		p("set / network-instance default protocols isis instance %s interface %s.0 ipv4-unicast admin-state enable", ISISInstance, ifc.Name)
		p("set / network-instance default protocols isis instance %s interface %s.0 circuit-type point-to-point", ISISInstance, ifc.Name)
	}
	p("")

	// SR-MPLS config intentionally absent — public srlinux image lacks the feature flag. See docs/architecture.md.

	isTMC := n.Role == RoleTMC
	if hasCabinet || isTMC {
		p("set / network-instance default protocols bgp admin-state enable")
		p("set / network-instance default protocols bgp autonomous-system %d", s.Metadata.ASN.Backbone)
		p("set / network-instance default protocols bgp router-id %s", n.LoopbackV4)
		p("set / network-instance default protocols bgp afi-safi ipv4-unicast admin-state enable")
		p("")
	}

	if hasCabinet {
		p("set / routing-policy policy export-cabinet-routes statement 10 match protocol isis")
		p("set / routing-policy policy export-cabinet-routes statement 10 action policy-result accept")
		p("set / network-instance default protocols bgp group cabinets afi-safi ipv4-unicast admin-state enable")
		p("set / network-instance default protocols bgp group cabinets export-policy [export-cabinet-routes]")
		p("")
		for _, ifc := range ifaces {
			if ifc.LinkKind != LinkKindCabinet {
				continue
			}
			peerNode := s.NodeByName(ifc.PeerNode)
			asn := 0
			peerCity := ""
			if peerNode != nil {
				asn = peerNode.ASN
				peerCity = peerNode.Site.City
			}
			p("set / network-instance default protocols bgp neighbor %s admin-state enable", ifc.PeerV4)
			p("set / network-instance default protocols bgp neighbor %s peer-as %d", ifc.PeerV4, asn)
			p("set / network-instance default protocols bgp neighbor %s peer-group cabinets", ifc.PeerV4)
			p("set / network-instance default protocols bgp neighbor %s description \"%s (%s)\"", ifc.PeerV4, ifc.PeerNode, peerCity)
			p("")
		}
	}

	if isTMC {
		p("set / network-instance default protocols bgp group tmc-ibgp afi-safi ipv4-unicast admin-state enable")
		for _, peer := range s.Nodes {
			if peer.Role != RoleTMC || peer.Name == n.Name {
				continue
			}
			p("set / network-instance default protocols bgp neighbor %s admin-state enable", peer.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s peer-as %d", peer.LoopbackV4, s.Metadata.ASN.Backbone)
			p("set / network-instance default protocols bgp neighbor %s peer-group tmc-ibgp", peer.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s transport local-address %s", peer.LoopbackV4, n.LoopbackV4)
			p("set / network-instance default protocols bgp neighbor %s description \"iBGP to %s\"", peer.LoopbackV4, peer.Name)
			p("")
		}
	}

	return nil
}
