package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

const (
	srlImage = ImageSRLinux
	frrImage = ImageFRR
)

// frrDaemons is the standard FRR daemons file with zebra+bgpd enabled.
// Cabinets run eBGP toward their parent hub; no other daemons needed.
const frrDaemons = `zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no

vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"

# Run daemons as root so they keep CAP_NET_ADMIN/CAP_SYS_ADMIN. The
# upstream frrouting/frr image ships binaries without file capabilities,
# so dropping to the 'frr' user strips the caps the routing daemons need
# (privs_init in mgmtd/zebra/bgpd fails with EPERM otherwise).
frr_user="root"
frr_group="root"
`

// clabIntf translates a spec interface name to its containerlab-flavored form.
// SR Linux uses "ethernet-1/N" internally but containerlab expects "e1-N".
// Linux kinds (FRR cabinets) keep their native "ethN" form.
func clabIntf(kind, intf string) string {
	if kind == "srlinux" && strings.HasPrefix(intf, "ethernet-") {
		// ethernet-1/3 -> e1-3 (containerlab expects hyphens, not slashes)
		short := strings.TrimPrefix(intf, "ethernet-")
		return "e" + strings.ReplaceAll(short, "/", "-")
	}
	return intf
}

// configFilename returns the renderer-emitted startup-config filename for a node.
func configFilename(n Node) string {
	if n.Kind == "frr" {
		return n.Name + ".frr"
	}
	return n.Name + ".cfg"
}

// WriteContainerlab writes the containerlab topology YAML for the spec, suitable
// for embedding in a Topology CR's spec.definition.containerlab field.
func WriteContainerlab(w io.Writer, spec *Spec) error {
	fmt.Fprintf(w, "name: %s\n", spec.Metadata.Name)
	fmt.Fprintln(w, "topology:")
	fmt.Fprintln(w, "  kinds:")
	fmt.Fprintln(w, "    nokia_srlinux:")
	fmt.Fprintf(w, "      image: %s\n", srlImage)
	// Default chassis type is ixr-d2l, a TOR with no MPLS / segment-routing
	// support. ixr-d3 is the smallest 7220 IXR variant that exposes the SR-MPLS
	// schema. Use the dashed form — the legacy `ixrd3` spelling is deprecated.
	fmt.Fprintln(w, "      type: ixr-d3")
	// FRR cabinets share daemons, snmpd.conf, and wrapper.sh; only the
	// per-node frr.conf is unique. Containerlab merges per-node binds with
	// kind-level binds, so the shared mounts live here.
	//
	// FRR 10.6's mgmtd/zebra/bgpd require CAP_NET_ADMIN + CAP_SYS_ADMIN, which
	// containerlab's `linux` kind doesn't grant by default. Without these the
	// daemons fail privs_init and watchfrr exits, crashlooping the cabinet.
	fmt.Fprintln(w, "    linux:")
	fmt.Fprintf(w, "      image: %s\n", frrImage)
	fmt.Fprintln(w, "      binds:")
	fmt.Fprintln(w, "        - configs/daemons:/etc/frr/daemons")
	fmt.Fprintln(w, "        - configs/snmpd.conf:/etc/snmp/snmpd.conf")
	fmt.Fprintln(w, "        - configs/wrapper.sh:/wrapper.sh")
	fmt.Fprintln(w, "      cmd: /wrapper.sh")
	fmt.Fprintln(w, "      cap-add:")
	fmt.Fprintln(w, "        - NET_ADMIN")
	fmt.Fprintln(w, "        - SYS_ADMIN")

	fmt.Fprintln(w, "  nodes:")
	for _, n := range spec.Nodes {
		fmt.Fprintf(w, "    %s:\n", n.Name)
		switch n.Kind {
		case "srlinux":
			fmt.Fprintln(w, "      kind: nokia_srlinux")
			fmt.Fprintf(w, "      startup-config: configs/%s\n", configFilename(n))
		case "frr":
			fmt.Fprintln(w, "      kind: linux")
			fmt.Fprintln(w, "      binds:")
			fmt.Fprintf(w, "        - configs/%s:/etc/frr/frr.conf\n", configFilename(n))
		}
	}

	fmt.Fprintln(w, "  links:")
	for _, l := range spec.Links {
		na := spec.NodeByName(l.A.Node)
		nb := spec.NodeByName(l.B.Node)
		fmt.Fprintf(w, "    - endpoints: [%q, %q]\n",
			fmt.Sprintf("%s:%s", l.A.Node, clabIntf(na.Kind, l.A.Intf)),
			fmt.Sprintf("%s:%s", l.B.Node, clabIntf(nb.Kind, l.B.Intf)),
		)
	}
	return nil
}

// WriteTopology writes the clabernetes Topology CR with embedded containerlab
// definition and per-node filesFromConfigMap mounts for startup configs.
func WriteTopology(w io.Writer, spec *Spec) error {
	p := newPrinter(w)
	var clab strings.Builder
	if err := WriteContainerlab(&clab, spec); err != nil {
		return err
	}

	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("apiVersion: clabernetes.containerlab.dev/v1alpha1")
	p("kind: Topology")
	p("metadata:")
	p("  name: %s", spec.Metadata.Name)
	p("spec:")
	// Expose only via ClusterIP services. Default LoadBalancer makes k3d's
	// klipper-lb fan out into per-node DaemonSet pods that port-collide
	// (12 pods × shared host ports), leaving dozens of svclb pods Pending.
	// gnmic + cut-fiber reach gNMI in-cluster, so ClusterIP is sufficient.
	p("  expose:")
	p("    exposeType: ClusterIP")
	p("  definition:")
	p("    containerlab: |-")
	for _, line := range strings.Split(strings.TrimRight(clab.String(), "\n"), "\n") {
		p("      %s", line)
	}
	p("  deployment:")
	p("    filesFromConfigMap:")
	// The clabernetes admission webhook defaults `mode: read` on any file
	// entry that omits it, so emit it explicitly to keep ArgoCD diffs clean.
	for _, n := range spec.Nodes {
		p("      %s:", n.Name)
		p("        - filePath: configs/%s", configFilename(n))
		p("          configMapName: topology-startup-configs")
		p("          configMapPath: %s", configFilename(n))
		p("          mode: read")
		if n.Kind == "frr" {
			p("        - filePath: configs/daemons")
			p("          configMapName: topology-startup-configs")
			p("          configMapPath: daemons")
			p("          mode: read")
			p("        - filePath: configs/snmpd.conf")
			p("          configMapName: topology-startup-configs")
			p("          configMapPath: snmpd.conf")
			p("          mode: read")
			p("        - filePath: configs/wrapper.sh")
			p("          configMapName: topology-startup-configs")
			p("          configMapPath: wrapper.sh")
			p("          mode: execute")
		}
	}
	return nil
}

// WriteTopologyKustomization writes a kustomization.yaml that bundles the
// Topology CR with a single ConfigMap containing every startup-config.
func WriteTopologyKustomization(w io.Writer, spec *Spec) error {
	p := newPrinter(w)
	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("apiVersion: kustomize.config.k8s.io/v1beta1")
	p("kind: Kustomization")
	p("")
	p("namespace: clabernetes")
	p("")
	p("resources:")
	p("  - topology.yaml")
	p("")
	p("generatorOptions:")
	p("  disableNameSuffixHash: true")
	p("")
	p("configMapGenerator:")
	p("  - name: topology-startup-configs")
	p("    files:")

	files := make([]string, 0, len(spec.Nodes)+1)
	for _, n := range spec.Nodes {
		files = append(files, "startup-configs/"+configFilename(n))
	}
	files = append(files, "startup-configs/daemons", "startup-configs/snmpd.conf", "startup-configs/wrapper.sh")
	sort.Strings(files)
	for _, f := range files {
		p("      - %s", f)
	}
	return nil
}

// WriteFRRDaemons writes the standard FRR daemons file enabling zebra+bgpd.
func WriteFRRDaemons(w io.Writer) error {
	if _, err := fmt.Fprintln(w, "# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*."); err != nil {
		return err
	}
	_, err := io.WriteString(w, frrDaemons)
	return err
}
