package main

import "io"

// WriteVersions emits a ConfigMap of canonical image versions used by
// every workload in the demo. The eventing and dom-synth manifests
// reference these via env-var indirection so version bumps land in one
// place.
func WriteVersions(w io.Writer) error {
	p := newPrinter(w)
	p("# Generated by tools/render — do not edit. Source: spec/atlanta.yaml + tools/render/*.")
	p("apiVersion: v1")
	p("kind: ConfigMap")
	p("metadata:")
	p("  name: atlas-demo-versions")
	p("  namespace: argo-events")
	p("data:")
	p("  srlinux: %q", ImageSRLinux)
	p("  frr: %q", ImageFRR)
	p("  python: %q", ImagePython)
	p("  gnmic: %q", ImageGNMIC)
	return nil
}
