name: argo-workflows
namespace: argo
syncWave: "0"
chart:
  repo: https://argoproj.github.io/argo-helm
  name: argo-workflows
  version: 1.1.1
  releaseName: argo-workflows
  values: platform/values/argo-workflows.yaml
