name: clabernetes
namespace: clabernetes
syncWave: "0"
chart:
  repo: ghcr.io/srl-labs/clabernetes
  name: clabernetes
  version: 0.5.0
  releaseName: clabernetes
  values: platform/values/clabernetes.yaml
