name: kube-prometheus-stack
namespace: monitoring
syncWave: "0"
chart:
  repo: https://prometheus-community.github.io/helm-charts
  name: kube-prometheus-stack
  version: 84.5.0
  releaseName: kps
  values: platform/values/kube-prometheus-stack.yaml
  skipCrds: false
